### ISSUE TITLE
`readerfy/2` is not working with returns that is not block

### ISSUE THREAD

**Issue by nallwhy** [jechol/defr#7]
```elixir
fn _ -> [] end
|> readerfy()
```

```
The following arguments were given to Defr.convert_do_block/1:
    
        # 1
        []
    
    Attempted function clauses (showing 2 out of 2):
    
        defp convert_do_block({:__block__, ctx, exprs})
        defp convert_do_block({_, ctx, _} = expr)

    (defr 0.4.0) lib/defr.ex:154: Defr.convert_do_block/1
    (defr 0.4.0) lib/defr.ex:53: anonymous fn/1 in Defr."MACRO-readerfy"/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.12.3) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (defr 0.4.0) expanding macro: Defr.readerfy/1
```

**Comment by jechol** [comment]
Thanks!

Fixed at https://github.com/jechol/defr/commit/8f077c67e30b53603b51cc8bbd6014d5b201a3a6
